# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-14 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_TipoProceso', models.CharField(max_length=10)),
                ('ID_EstadoProceso', models.CharField(max_length=10)),
                ('Cuantia', models.IntegerField(default=0)),
                ('CodigoEntidad', models.IntegerField(default=0)),
            ],
        ),
    ]
